### ISSUE TITLE
Jagged icon issue

### ISSUE THREAD

**Issue by ivoryguru** [BigslimVdub/AeonLW#5]
Have you ever seen this?
![ico](https://user-images.githubusercontent.com/69757456/104131878-05c87380-533f-11eb-9efa-d50c34d86e12.png)
I think this is related
https://forum.quasar-framework.org/topic/2827/windows-app-icon-with-electron-electron-builder-are-jagged/12
I would fix it my self but I am struggling to build it on windows.

**Comment by BigslimVdub** [comment]
FYI i'm pretty sure that this is caused by using the aeon packeged SVG's to creat an icn. WIndows is a pain to create these on without multiple img files. 

For windows I have not had an issue on windows 10. What specific issues are you having building?

**Comment by ivoryguru** [comment]
I just figured out the issue and made a PR #6
